ALTER TABLE "contract_members"
ADD COLUMN IF NOT EXISTS "full_name" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "phone" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "age" INTEGER,
ADD COLUMN IF NOT EXISTS "identity_card" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "identity_card_image_url" TEXT;
